### ISSUE TITLE
(non-expected) coma in the processed files

### ISSUE THREAD

**Issue by Colanim** [mahnazkoupaee/WikiHow-Dataset#11]
After running `process.py`, here is an example of the file produced (`articles/HowToCareforYourDogintheWinter1.txt`) :

> @summary
> 
> 
> 
> 
> 
> @summary
> 
> feed them more calories.,
> 
> 
> 
> @summary
> 
> adjust their food intake and schedule.,
> 
> 
> 
> @summary
> 
> give your dog fish oil supplements.,
> 
> 
> 
> @summary
> 
> provide them constant access to clean water.,
> 
> 
> 
> @summary
> 
> protect your dog from antifreeze poisoning.,
> 
> 
> 
> @summary
> 
> put out sleeping pads for your dogs.,
> 
> 
> 
> @summary
> 
> keep dogs inside as much as possible.,
> 
> 
> 
> @summary
> 
> provide adequate shelter if your dog does need to be left outside.
> 
> @article
> 
>  If your dog is a worker or goes outside a lot, they’ll be burning even more calories than normal to just stay warm. Any dog, even a house dog who goes outside a few times a day to do their business, will be using up slightly more calories simply regulating their body temperatures. To compensate for this, it’s a good idea to increase your dog’s caloric intake according to their increased expenditure of energy in the winter.The amount of extra calories will depend on your dog’s size, coat, age, activity level, and outdoor exposure as well as the severity of the climate. Most dogs will not require more than a 10% bump in their caloric intake, but outdoor working dogs could require nearly double the calories. Consult with your vet to get their winter diet recommendations for your pet.
> 
> While dogs do generally need more calories in the winter, they (like us) also have a greater tendency to overeat during the holiday season. If your dog starts to put on weight, go back to their normal diet and consult with your vet.;
> 
> , Besides generally needing more calories, dogs benefit from a more consistent caloric intake during the winter. The easiest way to add extra calories is to add a bit more food to your pet’s daily serving size. If you usually feed your dog once a day, consider switching to twice a day and increasing their overall daily serving so that your dog has a steadier caloric intake.
> 
> 
> 
> 
> 
> If your dog needs to significantly boost their calories, consider swapping their normal dog food for a higher-calorie formula. When switching foods, always be sure to monitor your dog to ensure that it is not causing any digestive issues. Watch for telling symptoms like vomiting or diarrhea.
> 
> It's not necessary to feed dogs hot food or warm water to help them stay warm. This can mess with digestion and upset your dog's stomach. It’s better to keep the dog's diet relatively stable.
> 
> 
> 
> , Fish oils offer natural lubricants that can benefit your dog during cold months. Adding more Omega 3 and Omega 6 fatty acids to your dog’s diet in the winter can help them stave off any potential weather-related irritations to their skin and paws.It can also be beneficial to older dogs in alleviating arthritis pain that’s exacerbated by cold conditions.
> 
> 
> 
> , We often forget that hydration is just as critical in the winter months as it is during the summer. Be sure that your pooch always has a dish of fresh water close at hand, even at night.If you have your dog outside, be sure to regularly check their water to make sure it isn’t frozen.
> 
> 
> 
> , We use antifreeze a lot in the winter, a substance that’s tasty but toxic to our pets. Be sure to keep it out of the reach of your dog on a high shelf or in a securely locked cupboard. Always clean up any spills immediately., If you have hardwood or tile floors, it can get awfully cold at night during the wintertime. Dogs, like you, enjoy being snug and cozy. When they struggle to find a warm spot, they can lose sleep or even disrupt yours with their restlessness. Buy some sleeping cushions or pads for your dog, or put out a couple old blankets for the dog to nest in., If the temperature drops below freezing, dogs should be inside far more than they’re out. In general, you don't want to leave dogs out for longer than you'd stay out in your winter coat. Even long-haired dogs can be susceptible to frostbite and hypothermia.
> 
> 
> 
> 
> 
> If your dog usually sleeps outside, try letting them sleep inside in a designated area (such as the garage, kitchen, or entryway) when it drops below freezing temperature in the winter.
> 
> 
> 
> , High winds and cold temperatures can be deadly for outdoor dogs. It's absolutely essential that you provide them with a dog house and wind-breaks.If you don’t already have one, buy or build a dog house. Keep your dog warmer by raising the floor of the dog house off the ground with raised flooring or palettes. Cover the bottom with thick, dry bedding (like blankets and straw) for your dog to nest in.
> 
> You can also consider purchasing a heated dog house for your pet. However, do not try DIY alternatives like space heaters or electric blankets since these can pose serious fire risks.

---

A few problems :

- First summary is empty
- Almost all summaries end with a non-expected coma (punctuation is already here)
- Some paragraph in the full article start with non-expected coma (at the beginning of sentence)

---

**Is it expected behavior ? If so, why ?**

**Comment by mahnazkoupaee** [comment]
The unexpected commas happened when crawling the WikiHow knowledge base. The summaries and the article paragraphs are first extracted and then concatenated to form the summary, article pair. This problem exists in the wikihowAll.csv file. However, the wikihowSep.csv can be used to generate the summaries and article pairs without the extra commas. The first summary is empty as the first line of the summary in the file is probably a new line, tab or space. This will not be an issue while using summarization systems as they ignore the whitespaces. 
I have also modified the code to remove theses unexpected punctuations as much as possible.
