### ISSUE TITLE
Empty texts in wikihowSep.csv

### ISSUE THREAD

**Issue by Colanim** [mahnazkoupaee/WikiHow-Dataset#12]
I'm trying to process myself the file `wikihowSep.csv` (rather than `wikihowAll.csv`, because each summary is associated to a specific text)

---

When processing the file, I noticed that approximately 15% of the data contain wrong text :

**`Data.ix[row, 'text']` return `nan` or `\n\n;\n`**

---

Is this expected ? If so, this summary is unusable, right ?

**Comment by mahnazkoupaee** [comment]
As you know, the Wikihow articles contain multiple steps. Each step starts with a bold line followed by a few sentences to further describe that line. In some articles and for some of their paragraphs, there is no description except the bold line. That is the reason for empty values in the results. We have used a threshold in our paper to remove such entries (short articles with long summaries as well as articles with no summary).
