### ISSUE TITLE
Preprocessing - unicode treatment

### ISSUE THREAD

**Issue by lambdaofgod** [mahnazkoupaee/WikiHow-Dataset#7]
How do you treat unicode characters in preprocessing? 
I was trying to run Abigail See's preprocessing scripts from [cnn-dailymail](https://github.com/abisee/cnn-dailymail) repository, but it throws errors in tokenizer (like for example `Untokenizable: ? (U+2061, decimal: 8289)`).

BTW cnn-dailymail needs to be heavily modified to adjust to your dataset - don't you just have code for that? Why not share it in a related repository?

**Comment by mahnazkoupaee** [comment]
Several Untokenizable: warnings from Stanford Tokenizer may be observed. These are related to Unicode characters in the data and it seems OK to ignore them.

I will also try to upload the code as soon as possible.
