### ISSUE TITLE
Handling of non-latin alphabets characters in preprocessing

### ISSUE THREAD

**Issue by lambdaofgod** [mahnazkoupaee/WikiHow-Dataset#9]
How do you handle characters from different alphabets in preprocessing? 

For example there is a headline

> Good luck!” is straightforward, heartfelt, and almost impossible to get wrong.\n\n\nMake sure that you sound sincere. If said in the wrong tone, this phrase can be interpreted as sarcasm. So make sure that the person understands your sincerity when you express the sentiment.\nSome people dislike the phrase because, they feel, it carries a note of negativity. “Good luck” for them implies that you have little to do with your own success.Use the phrase at your discretion.;\n, If you are dealing with someone who dislikes “Good luck!” or if you want a more creative English expression, there are other sayings that essentially mean the same thing. Try one of these depending on the situation.“Best of luck” or “hoping for the best” both carry the sentiment and are subtle variations.\nCrossing one’s fingers is often done to express a wish for luck, so you can also wish good luck by saying, “I’m keeping my fingers crossed.”\nSome actors feel that it is bad luck to say “Good luck!” before a performance. For this reason, it is traditionally better in the situation to “break a leg,” which refers to taking a bow at curtain call.While not an exact match, people sometimes borrow the phrase “May the force be with you” from Star Wars to wish people luck with a challenging task.\nOther English variants include, “Knock them dead!” “You’ll do great,” or “Blow them away!”, English is not the only language that has expressions for “Good luck,” of course. One way to stay fresh is to wish someone luck in a foreign language. This works especially well if the other person speaks that language or has some connection to its culture.In Spanish, wish someone “¡Buena suerte!” Both “Viel Glück!” and “Alles Gute!” can be used to express well wishes in German, while “Bonne chance!” works in French.\nIn Italian, try “Buona fortuna!” or “In bocca al lupo!”\n“Jūk néih hóuwahn” (祝你好運) is the Cantonese Chinese way of wishing luck, while “Gokoūn o inorimasu” (ご幸運を祈ります) is the formal way to wish good luck in Japanese. “Ganbatte ne” (頑張ってね) is the informal expression.\nWish someone luck in Greek with “kalí tíhi” (Καλή τύχη). “İyi şanslar” or “Bol şans!” work in Turkish.\n"Saubhāgya" (सौभाग्य) is the Hindi way of wishing good luck. In Arabic, try “Bi’t-tawfiq!”\n\n

Do you handle these characters in a special way, or just leave them as is?

**Comment by mahnazkoupaee** [comment]
No special preprocessing is done for them.
